# -- 코드를 입력하세요
# SELECT t2.USER_ID,t2.NICKNAME,SUM(t1.PRICE) AS TOTAL_SALES
# FROM USED_GOODS_BOARD t1, USED_GOODS_USER t2
# where t1.WRITER_ID = t2.USER_ID AND t1.STATUS = 'DONE'
# GROUP BY t2.USER_ID
# HAVING TOTAL_SALES >= 700000
# ORDER BY TOTAL_SALES ASC