# -- 코드를 입력하세요
# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# from REST_INFO
# Where (FOOD_TYPE, FAVORITES) IN (SELECT FOOD_TYPE, MAX(FAVORITES) From REST_INFO GROUP BY FOOD_TYPE)
# ORDER BY FOOD_TYPE DESC