# -- 코드를 입력하세요
# SELECT ICECREAM_INFO.INGREDIENT_TYPE, sum(FIRST_HALF.TOTAL_ORDER) AS TOTAL_ORDER
# From ICECREAM_INFO, FIRST_HALF
# where ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
# GROUP BY INGREDIENT_TYPE
# ORDER BY TOTAL_ORDER